script: "bundle exec rake"
notifications:
  email:
    - bram@craniumisajar.com
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - ree
gemfile:
  - spec/support/gemfiles/Gemfile.rails-3.0.x
  - spec/support/gemfiles/Gemfile.rails-3.1.x
env:
  - RAILS_ENV=test
